name: schoolms_portal
description: School Management System Portal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: KantumruyPro
      fonts:
        # Regular (400)
        - asset: assets/fonts/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/KantumruyPro-Italic.ttf
          weight: 400
          style: italic
 
        # Medium (500)
        - asset: assets/fonts/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/KantumruyPro-MediumItalic.ttf
          weight: 500
          style: italic
 
        # SemiBold (600)
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KantumruyPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
 
        # Bold (700)
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/KantumruyPro-BoldItalic.ttf
          weight: 700
          style: italic